version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: 'stackoverflow-elasticsearch'
    ports:
      - '9200:9200'
      - '9300:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    container_name: 'tackoverflow-kibana'
    image: kibana:7.10.1
    ports:
      - '5601:5601'

    
